# This is the name that will show up in the Actions sidebar
name: Ali Nuget publish test

# These are the events that can trigger the workflow
on:
  push:
    # These are the branches in which events can happen that will trigger the workflow
    branches: [ alisusanto-smu-patch-1 ]

env:
    GitHubPackageFeedUrl: https://nuget.pkg.github.com/Team-2-DevOps/index.json
    LogicProjectPath: ${{ github.workspace }}/AnimalAdoption.Common.Logic/AnimalAdoption.Common.Logic.csproj
      
# There can be multiple jobs that make up a pipeline
jobs:
  # This is the first (and only job at this stage) and it will show up with the name "build"
  build:
    # This is the agent type that the job will run on
    runs-on: ubuntu-latest

    # These are the steps inside the "build" job
    steps:
    # Step one
    - uses: actions/checkout@v2
    
    # Step two
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    # Step three
    - name: Restore dependencies
      run: dotnet restore
      
    # Step four
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    # Step six publish to "artifact" folder
    - name: publish
      run: dotnet pack ${{ env.LogicProjectPath }} --no-build --no-restore -o ${{ github.workspace }}/artifact --configuration Release
      
    # Step 7 take content of "artifact" folder and zip it up. zip file can be found in end of CI
    - name: List out directory contents
      run: |
          echo "Listing the contents of the GitHub workspace directory"
          ls ${{ github.workspace }}/artifact

    # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Push package to GitHub registry
      run: dotnet nuget push ${{ github.workspace }}/artifact/*.nupkg --skip-duplicate
